<a href="https://colab.research.google.com/github/Mahjabeenqamar1/GenAI-Essentials/blob/main/BERT_Embedding_simple.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# prompt: i want to implement simple embedding example using BERT

!pip install transformers

from transformers import BertTokenizer, BertModel
import torch

# Load pre-trained model tokenizer (vocabulary)
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Load pre-trained model (weights)
model = BertModel.from_pretrained('bert-base-uncased')

# Tokenize input
text = "Here is the sentence I want embeddings for."
encoded_input = tokenizer(text, return_tensors='pt')

# Compute token embeddings
with torch.no_grad():
    model_output = model(**encoded_input)

# Perform pooling. In this case, we are using the first token ([CLS] token) embedding.
sentence_embedding = model_output[0][:, 0, :]

sentence_embedding


/usr/local/lib/python3.11/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

tensor([[-3.8822e-02, -4.9612e-02,  6.8123e-02, -2.9851e-01, -2.9840e-01,
         -3.0843e-01,  3.0120e-02,  2.0229e-01,  1.8005e-01, -1.4553e-01,
          2.0532e-01,  1.4376e-02, -6.0990e-02,  6.6026e-02,  3.2963e-01,
          3.7978e-03, -2.1175e-01,  3.7744e-01,  1.4625e-01, -2.0243e-01,
          1.7214e-01, -5.8758e-02,  3.3684e-02, -2.2808e-01,  1.8304e-01,
         -3.0446e-02, -4.9751e-02, -1.2970e-01, -1.9525e-01,  9.2727e-02,
          6.3092e-02,  1.2827e-01, -1.8259e-01, -1.0227e-01,  2.3424e-01,
          1.1938e-01,  3.1091e-01, -2.5228e-01,  2.8242e-01, -2.4837e-01,
         -2.3287e-01, -8.0088e-04,  2.2632e-01, -1.1506e-01,  1.1957e-01,
         -3.0994e-01, -2.9033e+00, -1.6620e-01, -3.3403e-01, -1.8791e-01,
         -1.3200e-02, -3.5992e-02,  2.9946e-01,  2.8467e-01,  9.2990e-02,
          9.8315e-02, -2.5048e-01,  3.2162e-01,  1.9736e-01, -1.2443e-01,
          1.7249e-01,  2.9085e-01,  2.3596e-03,  8.8090e-03, -2.6255e-01,
          3.1879e-01, -1.2396e-01,  1.

In [ ]:
# prompt: i want to implement sinmple embadding example using
# cl-tohoku-bert-base-japanese

from transformers import BertTokenizer, BertModel
import torch

!pip install transformers sentencepiece

# Load pre-trained model tokenizer (vocabulary)
tokenizer = BertTokenizer.from_pretrained('cl-tohoku/bert-base-japanese')

# Load pre-trained model (weights)
model = BertModel.from_pretrained('cl-tohoku/bert-base-japanese')

# Tokenize input
text = "これは、日本語の文章の例です。"
encoded_input = tokenizer(text, return_tensors='pt')

# Compute token embeddings
with torch.no_grad():
    model_output = model(**encoded_input)

# Perform pooling. In this case, we are using the first token ([CLS] token) embedding.
sentence_embedding = model_output[0][:, 0, :]

sentence_embedding


tokenizer_config.json:   0%|          | 0.00/120 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/258k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/479 [00:00<?, ?B/s]

The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'BertJapaneseTokenizer'. 
The class this function is called from is 'BertTokenizer'.


pytorch_model.bin:   0%|          | 0.00/445M [00:00<?, ?B/s]

tensor([[ 1.1622e+00,  1.9074e-01, -6.6465e-02, -3.5940e-02, -5.4318e-01,
          1.6330e-01,  3.2871e-01, -1.0624e-01, -5.1590e-01, -7.0534e-01,
          3.5318e-01, -7.1715e-01, -2.3516e-01, -4.6189e-01,  3.6464e-01,
          2.0148e-01,  1.5384e-01, -3.5482e-01,  4.3116e-01,  4.8182e-02,
         -3.4989e-01,  2.6658e-01,  2.3044e-01,  4.5998e-01,  1.6327e-02,
          2.5140e-01,  1.0253e-01,  1.2011e-02,  8.5436e-02,  1.1920e-02,
         -3.2380e-01, -3.8023e-01,  2.4236e-01,  3.3595e-01,  8.0317e-01,
          6.3455e-01,  2.2887e-01, -9.2743e-02, -1.3013e-01, -7.2259e-01,
         -4.9440e-03, -1.4537e-01, -3.5997e-01,  1.5055e-01, -4.8100e-01,
          2.7634e-01,  7.3753e-02,  4.8116e-02,  8.3267e-01,  1.6824e-01,
         -1.3544e-01,  7.0154e-01,  1.2113e-01,  7.2015e-02,  7.8021e-01,
         -4.5351e-01, -2.8653e-01, -1.0535e-01,  2.9914e-02,  4.3385e-01,
         -3.6841e-01,  2.4969e-01,  2.2315e-02, -1.8412e-01, -3.0543e-01,
          1.2576e-01,  1.6802e-01, -3.

In [ ]:
import torch
from transformers import AutoModel, AutoTokenizer

bertweet = AutoModel.from_pretrained("vinai/bertweet-base")

# For transformers v4.x+:
tokenizer = AutoTokenizer.from_pretrained("vinai/bertweet-base", use_fast=False)

# For transformers v3.x:
# tokenizer = AutoTokenizer.from_pretrained("vinai/bertweet-base")

# INPUT TWEET IS ALREADY NORMALIZED!
line = "SC has first two presumptive cases of coronavirus , DHEC confirms HTTPURL via @USER :cry:"

input_ids = torch.tensor([tokenizer.encode(line)])

with torch.no_grad():
    features = bertweet(input_ids)  # Models outputs are now tuples

# With TensorFlow 2.0+:
# from transformers import TFAutoModel
# bertweet = TFAutoModel.from_pretrained("vinai/bertweet-base")

config.json:   0%|          | 0.00/558 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/543M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/543M [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/843k [00:00<?, ?B/s]

bpe.codes:   0%|          | 0.00/1.08M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/2.91M [00:00<?, ?B/s]

emoji is not installed, thus not converting emoticons or emojis into text. Install emoji: pip3 install emoji==0.6.0


In [ ]:
from transformers import AutoTokenizer, BertModel
import torch

tokenizer = AutoTokenizer.from_pretrained("google-bert/bert-base-uncased")
model = BertModel.from_pretrained("google-bert/bert-base-uncased")



In [ ]:
inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")
outputs = model(**inputs)



In [ ]:
last_hidden_states = outputs.last_hidden_state

In [ ]:
last_hidden_states

tensor([[[-0.1144,  0.1937,  0.1250,  ..., -0.3827,  0.2107,  0.5407],
         [ 0.5308,  0.3207,  0.3665,  ..., -0.0036,  0.7579,  0.0388],
         [-0.4877,  0.8849,  0.4256,  ..., -0.6976,  0.4458,  0.1231],
         ...,
         [-0.7003, -0.1815,  0.3297,  ..., -0.4838,  0.0680,  0.8901],
         [-1.0355, -0.2567, -0.0317,  ...,  0.3197,  0.3999,  0.1795],
         [ 0.6080,  0.2610, -0.3131,  ...,  0.0311, -0.6283, -0.1994]]],
       grad_fn=<NativeLayerNormBackward0>)

In [ ]:
from transformers import AutoTokenizer, BertForMaskedLM
import torch

tokenizer = AutoTokenizer.from_pretrained("google-bert/bert-base-uncased")
model = BertForMaskedLM.from_pretrained("google-bert/bert-base-uncased")

inputs = tokenizer("The capital of France is [MASK].", return_tensors="pt")

with torch.no_grad():
    logits = model(**inputs).logits

# retrieve index of [MASK]
mask_token_index = (inputs.input_ids == tokenizer.mask_token_id)[0].nonzero(as_tuple=True)[0]

predicted_token_id = logits[0, mask_token_index].argmax(axis=-1)
tokenizer.decode(predicted_token_id)

labels = tokenizer("The capital of France is Paris.", return_tensors="pt")["input_ids"]
# mask labels of non-[MASK] tokens
labels = torch.where(inputs.input_ids == tokenizer.mask_token_id, labels, -100)

outputs = model(**inputs, labels=labels)
round(outputs.loss.item(), 2)

BertForMaskedLM has generative capabilities, as `prepare_inputs_for_generation` is explicitly overwritten. However, it doesn't directly inherit from `GenerationMixin`. From 👉v4.50👈 onwards, `PreTrainedModel` will NOT inherit from `GenerationMixin`, and this model will lose the ability to call `generate` and other related functions.
  - If you're using `trust_remote_code=True`, you can get rid of this warning by loading the model with an auto class. See https://huggingface.co/docs/transformers/en/model_doc/auto#auto-classes
  - If you are the owner of the model architecture code, please modify your model class such that it inherits from `GenerationMixin` (after `PreTrainedModel`, otherwise you'll get an exception).
  - If you are not the owner of the model architecture class, please contact the model code owner to update it.
Some weights of the model checkpoint at google-bert/bert-base-uncased were not used when initializing BertForMaskedLM: ['bert.pooler.dense.bias', 'bert.pooler.dense

0.88